#ifndef ERRDEF_H
#define ERRDEF_H

#define ERR_BOOT
#define ERR_BOOT_INEXISTENT
#define ERR_BOOT_UNREADABLE
#define ERR_BOOT_NOTFOUND
#define ERR_SDCARD_NORESPONSE
#define ERR_SDCARD_INIT
#define ERR_SDCARD_BADRESPONSE
#define ERR_SDCARD_PARTUNREADABLE
#define ERR_SDCARD_BLOCKUNREADABLE
#define ERR_SDCARD_TIMEOUT
#define ERR_SDCARD_UNHANDLEDRESPONSEEXPECTION
#define ERR_SDCARD_UNSUPPORTEDFS
#define ERR_SDCARD_ANALYZEERROR
#define ERR_SDCARD_NOROOT
#define ERR_SDCARD_NULLSECTOR
#define ERR_SDCARD_UNSKIPABLE


#endif // ERRDEF_H
